import { StyleSheet } from "react-native";
import { appColors } from "./StyleAttributes";

export const SearchStyles = StyleSheet.create({
  absoluteBox: {
    zIndex: 5,
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 15,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 12,
  },
  absoluteDisclaimer: {
    zIndex: 5,
    position: "absolute",
    left: 0,
    right: 0,
    top: 25,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 12,
  },
  noResults: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    backgroundColor: appColors.background,
    borderRadius: 8,
    shadowColor: "#171717",
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: 50,
  },
  searchPrompt: {
    paddingVertical: 6,
    paddingHorizontal: 15,
    backgroundColor: appColors.background,
    borderRadius: 8,
    shadowColor: "#171717",
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
});
